version: '3'


services:
  spring-boot-docker-prod-app:
    image: springboot-prod-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '80:5000'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
